### ISSUE TITLE
有关css中的某些class

### ISSUE THREAD

**Issue by unnamed42** [Haojen/hexo-theme-Anisina#11]
请问css中，如下class:
.t
.section-heading
.captain
.floating-label-form-group
.floating-label-form-group-with-value
.floating-label-form-group-with-focus
我在主题模板中找遍了也没有找到这几个class的存在，请问是否可以删去这些class呢？

**Comment by Haojen** [comment]
@unnamed42  ，可以自行测试删掉后是否有影响 ：）
