### ISSUE TITLE
没有找到anisina文件夹下的config.yml文件

### ISSUE THREAD

**Issue by wongsihan** [Haojen/hexo-theme-Anisina#15]
安装说明中的SNS settings去哪个文件找呢

**Comment by wongsihan** [comment]
还有就是首页里的头像呀，标签呀在哪设置呢。。。没有config文件找不到位置呀

**Comment by Haojen** [comment]
@envyandgreed  我的疏忽, 稍后会奉上最新的 `_config.yml` 文件, 然后复制该文件到 hexo 根目录替换就好了 : )

**Comment by wongsihan** [comment]
thanks~
