### ISSUE TITLE
参数config["post-default-img"]为undefined

### ISSUE THREAD

**Issue by 2ue** [Haojen/hexo-theme-Anisina#17]
config["post-default-img"]获取为undefined，config.title和post[head-img]能够正常获取

**Comment by Haojen** [comment]
@2ue  导致这个问题的原因是你没有设置默认的图片路径, 或者路径配置的有问题, yaml 语法 key 和 value 之间是需要一个空格的哟 : )

**Comment by 2ue** [comment]
应该不是这个原因。因为我在Anisina主题内配置post-default-img这个参数报undefined，但是在hexo的_config.yml下配置就没有问题。我的默认图片放置位置：themes\Anisina\source\img。

**Comment by Haojen** [comment]
@2ue  因为 Anisina 下的 `_config` 文件需要拷贝到 hexo 下, 我的readme已经有写, 你粗心啦~~ 😄

**Comment by Haojen** [comment]
@2ue  不过问题解决了就行 , 周末愉快 :D
