### ISSUE TITLE
social link is not working

### ISSUE THREAD

**Issue by scotthou94** [Haojen/hexo-theme-Anisina#19]
I followed the guide your provided:

```
    SNS settings
    github_username: scotthou94     # modify this account to yours
```

But nothing happened, no github link is displayed in the sidebar.
should I provide the full address of my github account?

**Comment by Haojen** [comment]
@scotthou94  when you change `_config` file , after you must run this command in your terminal `hexo clean && hexo g`

**Comment by scotthou94** [comment]
@Haojen I tried to run the `hexo clean` `hexo g` but it still doesn`t work. 
I basiclly copied the `_config` file in your repository into my own site`s `_config`, is there something else I should do to make things work besides setting the `github_username`?

**Comment by unnamed42** [comment]
You need to import font-awesome.min.css in https protocol.

**Comment by scotthou94** [comment]
@unnamed42 I assume the font-awesome.min.css should go into the theme`s layout? care to elaborate a little? I`m not quite clear what to do.

**Comment by unnamed42** [comment]
@scotthou94 it's located in `THEME_FOLDER/layout/_partial/head.ejs`, line 33. Just add a single `s` to its url.

**Comment by winston-wen** [comment]
@unnamed42 Thanks for your advise. I've just encountered a same issue as @scotthou94 .

**Comment by scotthou94** [comment]
@unnamed42 thanks in advance, I changed the protocol to https and run the `hexo clean` and `hexo d -g` command but still no github link appeared on the sidebar. I`m not sure what went wrong.
@DavaiZa did changing the protocol solve your problem?

**Comment by winston-wen** [comment]
@scotthou94 Yes, it worked on my blog https://davaiza.github.io

**Comment by unnamed42** [comment]
@scotthou94 I visited your site, and font-awesome.min.css is still unavailable. Maybe you should try `https://cdn.bootcss.com/font-awesome/4.6.3/css/font-awesome.min.css` or something else instead. The original cdn does not seem to support https.

**Comment by Haojen** [comment]
@scotthou94  , this issue will fix on next version , come soon ~

**Comment by Haojen** [comment]
@scotthou94  this issue  is have fix it~

**Comment by scotthou94** [comment]
@Haojen could you tell me what I should do to fix the problem? start over again or just make some change on the `.css`

**Comment by Haojen** [comment]
@scotthou94  can i speak chinese ?

**Comment by scotthou94** [comment]
@Haojen 当然当然

**Comment by Haojen** [comment]
现在具体什么问题?

**Comment by scotthou94** [comment]
@Haojen 社交链接的图标没有显示，你可以去[我的网站](https://scotthou94.github.io/)看一下，图片暂时没上传。
我根据教程在站点的配置文件里配置了`github_username: scotthou94`，和twitter的账号，但是并没有图标出现。
更改了`http`协议至`https`协议也没有使图标出现。
现在不清楚是什么问题。感谢解答。

**Comment by Haojen** [comment]
@scotthou94  刚才看了你的网站, 问题和主题无关, 是你的图片路径配置错了

社交链接不显示, 这个问题我在下个版本已经修复了, 这周末应该会发布新版本, 还请耐心 : )

**Comment by scotthou94** [comment]
@Haojen 不知道我现在应该怎么修改才能使社交链接显示呢

**Comment by Haojen** [comment]
@scotthou94  直接重新克隆新主题到本地就可以了

**Comment by scotthou94** [comment]
@Haojen 解决了，谢谢
