### ISSUE TITLE
why there's no index.html in the tags folder?

### ISSUE THREAD

**Issue by jarviswwong** [Haojen/hexo-theme-Anisina#2]
why there's no index.html in the tags folder? And i can't open the tags pages....

**Comment by Haojen** [comment]
@yyijian  you must use `hexo new page 'tags'` ceate a tags page show the navbar , then open the `Tags/index.md` file, set `layout: tags` , done :)

**Comment by jarviswwong** [comment]
thanks :)  Solved this problem!  And i hope that this theme has more updates!
