### ISSUE TITLE
tags are not working

### ISSUE THREAD

**Issue by HuaizhengZhang** [Haojen/hexo-theme-Anisina#22]
I just create tags, but it looks like this:

 blog
Untitled
Untitled
Untitled
Untitled
Untitled
Untitled
Untitled

Why this happend?

**Comment by perixiaowan** [comment]
did you use the layout that called 'tags' in the  tags/index.md?

**Comment by HuaizhengZhang** [comment]
@perixiaowan I find my hexo version is 2.8.3. I update it to 3.2.2. Everything is fine. Thanks for your reply.

**Comment by perixiaowan** [comment]
I visited you page find a file maybe conflict with the theme.The file name is 'http://s.swiftypecdn.com/install/v2/st.js' ,remove it and try to deploy your blog again?
