### ISSUE TITLE
post-default-img显示问题

### ISSUE THREAD

**Issue by budaig** [Haojen/hexo-theme-Anisina#24]
博主，您好，
在根目录下的_config.xml默认设置了post-default-img
后，诗歌类，在文章列表会显示默认的post-default-img图片。
![fireshot capture 3 - - http___localhost_4000_](https://cloud.githubusercontent.com/assets/18586226/18300856/81bc1f0a-74ff-11e6-90e6-4eeec9c058c6.png)

博文的 front-matter 上指定图片header-img后，进入文章页面，背景图片也默认被设置成了该header-img。能否增加一个分别设定文章列表背景图和header-img的设置项？毕竟有些header-img不适合做背景图。

另外，诗歌的排版能否考虑增加从右到左的选项，感觉这样一些古体诗词更有韵味。

谢谢。

**Comment by Haojen** [comment]
@budaig  很难碰到有同喜欢古体诗词的同学, 你是第一位. 非常感谢你详细的反馈, 我向你保证这1-2天将上述问题解决. 另外可否提供阁下的博客链接? 以便我刚更好的排除错误 : )

再次感谢使用主题

**Comment by budaig** [comment]
@Haojen 多谢及时回复。博客 [http://bdg.zhinuo.space](http://bdg.zhinuo.space)。
说不上多喜欢古体诗词，只是偶尔无病呻吟而已。不像你，专门作了诗词展现的网站。

刚刚又发现一个问题。tags标签页面，似乎在主页后第一个/后自动增加了一个空格，导致找不到文章。如你的tags页面下，Anisina-中文使用教程此文的链接变为 http://haojen.github.io/ 202016/08/06/Anisina-中文使用教程/。我的也有同样问题。

补充一下：出现上面诗歌类，在文章列表显示post-default-img图片的，似乎是在文章 front-matter ，加入了 cdn: 'header-off'，这样的配置。其他没有加入cdn配置的不会显示默认背景图片。

另外诗词类，在文章列表下，鼠标悬停时，从标题日期到节选内容都有下划线，希望修正。

谢谢。

非常漂亮，简洁的主题，博主加油。

**Comment by budaig** [comment]
对了，手机模式下，诗词类文章的Previous Post和Next post导航按钮好像不能用。不知是不是我浏览器的问题。请测试下。

不只是诗词类下文章导航栏，好像所有文章页面的前后篇导航栏，也在主页后第一个/后自动增加了一个空格

**Comment by Haojen** [comment]
@budaig  已经修复上述所有 bug ,请更新到最新版查看 : ) 
出现上述问题的原因是使用了某代码编辑器的代码自动格式化工具, 导致对代码进行了错误的缩放, 所以会出现跳转链接出现空格的乌龙现象, 上述几乎所有的问题都是因此导致~

**Comment by budaig** [comment]
@Haojen 
问题好像依旧。
tags 页面的链接没有修复，自动会在http://www.home.com/ 后自动添加空格。
PC端，手机端，文章页面的Previous Post和Next post导航按钮也自动在http://www.home.com/ 后自动添加空格。
手机端，诗词类文章页面的Previous Post和Next post导航按钮，悬停无 js 动作。

**Comment by Haojen** [comment]
@budaig  现在我修复了tag的问题, 其它的问题我昨天已经测试过, 貌似在我的blog上没有再次出现上述的问题了? 会不会是你更新代码后, 还是有手机缓存的原因呢?

**Comment by Haojen** [comment]
@budaig 关于手机端诗词网页的上一页和下一页的确有这个问题, 我看今天找个时间看能不能修复它

**Comment by budaig** [comment]
@Haojen 
是的，是缓存问题。都OK了。谢谢你的及时回复。
下面的不着急，如果你有时间再修正吧。
  手机端诗词网页的上一页和下一页的问题
  增加诗词从右至左的排版
  还有如果不麻烦的话，分开设定header-img和文章页面背景图片的设置。
谢谢了。

**Comment by manoloide** [comment]
Hello! sorry my english. Problem the next page and previus page. It gets fixed, eraser two space in code. 

post.ejs line 102
`<a href="<%- config.root %> <%- page.prev.path %>" data-toggle="tooltip" data-placement="top"`
for 
`<a href="<%- config.root %><%- page.prev.path %>" data-toggle="tooltip" data-placement="top"`

post.ejs line 108
`<a href="<%- config.root %> <%- page.next.path %>" data-toggle="tooltip" data-placement="top"`
for 
`<a href="<%- config.root %><%- page.next.path %>" data-toggle="tooltip" data-placement="top"`

**Comment by budaig** [comment]
@manoloide, hi. sorry, tried to update, but with no luck, it did not work.
the problem occours on poetry post pages, when browsering with mobile phones, the Next and Previous post buttons below the post content do not to work while with PC browser, they are fine.

anyway. thanks for your help.

**Comment by scotthou94** [comment]
我的图片的url是`https://cloud.githubusercontent.com/assets/17608374/18460735/a7176fd8-79a6-11e6-8e5d-0c14ba375f95.jpg`，想将其设为post-default-img，这是我的`_config`：

```
cdn-url: "https://cloud.githubusercontent.com/assets/17608374/18460735/"      # images cdn path

# 博文默认图片(如果不设置这一项, 博文标题的图片默认是灰色的)
post-default-img: a7176fd8-79a6-11e6-8e5d-0c14ba375f95.jpg
```

图片并没有显示，不知道是哪里设置的不对呢

**Comment by matrix-42** [comment]
请问能调用放在本地image吗?

谢谢

**Comment by perixiaowan** [comment]
可以调用，你是在文章里调用还是代码里调用？

文章调用的话，用markdownpro，在网上找个注册码。

代码里调用，可以把在主题下面和js、css并列添加一个img，把图片放在里面即可。

在2016年09月25日 02:36，d 写道:

请问能调用放在本地image吗?

谢谢

**Comment by matrix-42** [comment]
@perixiaowan 我是想把每个post 的 header image 放在本地, [就像这个一样.](https://github.com/Huxpro/huxpro.github.io) 
 ##不知道image该存在哪, 调用时front-matter该怎么写.

**Comment by wuhulala** [comment]
楼主  主页页面显示黑框框  https://wuhulala.github.io/  暂时没有找到解决方案 期待您的回复

**Comment by HongqinMa** [comment]
大神楼主，我有个小问题，我想在我的博文的配置header-img 配置完之后需要的是http:// 而不是https:// 怎么解决，找了好久不知道在哪里改，求教。。。
