### ISSUE TITLE
page.ejs在deploy时提示body未定义？

### ISSUE THREAD

**Issue by 2ue** [Haojen/hexo-theme-Anisina#25]
请问这是需要安装神马插件么？
![image](https://cloud.githubusercontent.com/assets/13751432/18476901/56956922-79fe-11e6-9230-1b3ca96d173a.png)

**Comment by xiaolongnk** [comment]
我也遇到过这个问题，可以带上 --debug 来观察到底是那篇文章引起了这个问题，然后找到那个对应的md就可以解决问题了。多半是因为一个没有内容，只有标题的markdown文件引起的。

hexo g --debug
