### ISSUE TITLE
怎样使tags根据频率显示不同色彩?

### ISSUE THREAD

**Issue by matrix-42** [Haojen/hexo-theme-Anisina#28]
我按照步骤设置tags, 现在tags都是灰色的, 并没有任何颜色.
不知道是不是有什么需要额外设置的地方?

**Comment by perixiaowan** [comment]
不需要设置，它会根据你的文章设置的标签，进行统计，根据标签使用的热度自动对颜色进行加深处理。我看了下你的博客，目前只有一篇，且标签都只使用一次，所以都是灰色的。

**Comment by matrix-42** [comment]
@perixiaowan 我加更多的博客, 依然是这样, 很奇怪.
不过谢谢哈, 我再研究研究

**Comment by perixiaowan** [comment]
(index):773 Mixed Content: The page at 'https://matrix-42.github.io/tags/' was loaded over HTTPS, but requested an insecure script 'http://matrix-42.github.io/js/jquery.tagcloud.js'. This request has been blocked; the content must be served over HTTPS.

我看了你的网页，你的标签上没有样式，你看看不加安全的http访问是否正常？如果正常的话，而你又想通过https访问，可以将链接更改为“https://matrix-42.github.io/js/jquery.tagcloud.js”    这个js和标签的颜色相关

**Comment by matrix-42** [comment]
@perixiaowan 将 config 里的 url 改为 https 开头, 问题得以解决.
十分感谢
请问你用的什么Debug工具, 不是做前端的不太懂.

**Comment by perixiaowan** [comment]
chrome即可调试，f12；
Firefox也行，需要装个firebug插件

**Comment by perixiaowan** [comment]
Firefox也行，需要装个firebug插件

**Comment by matrix-42** [comment]
@perixiaowan Many thanks!

**Comment by perixiaowan** [comment]
不客气

**Comment by zhangchione** [comment]
@matrix-42  你好，能不能详细说下，是哪个config里面的url？ 我也遇到了和你同样的问题
