### ISSUE TITLE
那个/my-works/是如何添加上去的，我想添加一个别的比方说/users/的子页面

### ISSUE THREAD

**Issue by yuzai** [Haojen/hexo-theme-Anisina#29]
现在我也写了一个主题，但是只有host ， host/archive/，想自己添加一个/users的页面，但是试了几次，最后浏览器看到的都是Cannot get /users/。
应该是布局文件的设置有问题。我就想问一下，怎么修改layout里面的.ejs文件，可以让我访问我新增加的/users页面

**Comment by yuzai** [comment]
就是怎么增加页面的路由，比方说localhost:5000.我可以访问localhost:5000/archives以及localhost:5000，如何新增一个文件，像你那样，可以访问localhost:5000/my-works/的。不是用的你的主题。是我自己正在写

**Comment by perixiaowan** [comment]
hexo new page users  ?

**Comment by yuzai** [comment]
这样可以吗？。。。我想用layout.ejs继续渲染。。这个主题直接clone，并没有hexo new page users就可以访问/my-workers/了

**Comment by perixiaowan** [comment]
试一下吧，然后在source里会生成users目录，在users目录下，有个index.md，加上你的layout（ejs文件）即可（例如layout: works）

**Comment by yuzai** [comment]
我试了一下，可以的。不过在新的layout（比如：work.ejs）里面不能访问hexo命名的一些函数。。。
这个作为主题当别人使用的时候应该是不需要重新hexo new page users了吧。。。

**Comment by perixiaowan** [comment]
不明白你的意思

发自网易邮箱大师
在2016年09月26日 19:06，yuzai 写道:

我试了一下，可以的。不过在新的layout（比如：work.ejs）里面不能访问hexo命名的一些函数。。。
这个作为主题当别人使用的时候应该是不需要重新hexo new page users了吧。。。

**Comment by yuzai** [comment]
是我弄错了。。可以使用的。问题已经解决啦
