### ISSUE TITLE
在写一个主题，但是tags处遇到了问题

### ISSUE THREAD

**Issue by yuzai** [Haojen/hexo-theme-Anisina#30]
用list_tag()产生了标签的连接，在tag.ejs中也写了相应的代码。
![image](https://cloud.githubusercontent.com/assets/16518346/19033663/3037899c-8992-11e6-96d4-38b801bd7a47.png)
现在的问题是，我点击标签，在使用hexo s的时候，可以链接到有该tag的页面，我在tag.ejs中使用了page.posts.each函数，但是当我hexo g的时候，报错，说page.posts.each没有定义。
![image](https://cloud.githubusercontent.com/assets/16518346/19033751/9e456e72-8992-11e6-8c2e-dd3948514ce2.png)
![image](https://cloud.githubusercontent.com/assets/16518346/19033775/b77b562c-8992-11e6-835d-c5e11cad3fcd.png)
但是当我直接使用Hexo s的时候可以链接到对应的tag页面，而且控制台也没有任何错误
这个是我的地址。上面有tag，但是tag.ejs中没有写东西。写东西之后hexo g就出错了。很多地方显示的就有问题。https://yuzai.github.io/
我的代码：https://github.com/yuzai/exo_theme
这个版本的是在tag.ejs中使用了page.posts.each(),直接使用Hexo s可以正常工作且不报错，但是如果hexo g就会报上面的错误。很困惑

**Comment by yuzai** [comment]
不过最后，虽然hexo g报错了。但是hexo d上去的效果跟hexo s的效果一样。。

**Comment by unnamed42** [comment]
page.posts.forEach
你要是不生成(g)的话那么部署(d)和预览(s)的还是你最后一次正确生成的内容

**Comment by yuzai** [comment]
hexo 生成过程虽然报错，但是生成完毕了。最后的结果是，hexo d上去之后page.posts.each是可以用的，这个函数的使用是和我预想的一样的。
最后的结果和使用了page.posts.each是一样的效果。不管了，谢啦
