### ISSUE TITLE
 WARN  No layout: index.html

### ISSUE THREAD

**Issue by yellowstarhx** [Haojen/hexo-theme-Anisina#33]
在执行git clone https://github.com/Haojen/hexo-theme-Anisina.git 后，将文件放入theme文件夹下，更改config的theme，执行hexo s，http://localhost:4000/  页面空白。
debug显示
WARN  No layout: index.html
GET / 200 8.630 ms - -
15:29:39.221 WARN  No layout: index.html
GET / 200 0.891 ms - -
15:29:39.665 WARN  No layout: index.html
GET / 200 0.796 ms - -
15:29:39.842 WARN  No layout: index.html
GET / 200 0.381 ms - -
15:29:40.003 WARN  No layout: index.html
GET / 200 0.396 ms - -
15:29:40.161 WARN  No layout: index.html
GET / 200 0.343 ms - -
15:29:40.305 WARN  No layout: index.html
GET / 200 0.581 ms - -
请问这是什么意思呀

把主题设为landscope显示是正常的

**Comment by Haojen** [comment]
@yellowstarhx 请阅读使用教程
