### ISSUE TITLE
 根据 markdown 生成的 TOC 锚点的内容是 undefined 

### ISSUE THREAD

**Issue by momaek** [Haojen/hexo-theme-Anisina#34]
<img width="1277" alt="screen shot 2016-10-16 at 22 54 06" src="https://cloud.githubusercontent.com/assets/3843588/19418292/7fe3a884-93f3-11e6-955d-fbfeab88cc4d.png">

看左下角 `#` 后面是undefined

**Comment by Haojen** [comment]
@momaek  多谢告知, 最近会抽时间修复它 : )

**Comment by Haojen** [comment]
@momaek 阁下是否更换过 markdown 的解析引擎? 我现在正排查出现这个问题的原因, 正在怀疑是更换 markdown 解析引擎导致的

**Comment by ttimasdf** [comment]
应该不是吧……毕竟 @Haojen 博主[自己的博客](https://haojen.github.io/2016/07/18/%E7%B2%92%E5%AD%90%E6%95%88%E6%9E%9C%E6%BA%90%E7%A0%81%E5%89%96%E6%9E%90/#undefined)TOC也是undefined［斜眼］

**Comment by Haojen** [comment]
@ttimasdf  因为鄙人的 markdown 解析引擎不是默认的哟~

**Comment by khiav223577** [comment]
這篇可以解決 undefined 的問題：https://github.com/hexojs/hexo-renderer-markdown-it/issues/40

**Comment by ttimasdf** [comment]
刚刚看了一眼markdown-it的文档突然想起来这个问题（然后戳了一下 @Haojen 的博客TOC依旧是undefined）。这个问题就是因为TOC锚点生成默认是关闭的需要手动开启（摔）。解决方案就是在博客`_config.yml`的markdown-it设置里面加上，
```yml
markdown:
  anchors:
    level: 1
    permalinkSymbol: ''
```
默认设置在[这里](https://github.com/hexojs/hexo-renderer-markdown-it/wiki/Advanced-Configuration)
