### ISSUE TITLE
hexo g 报错（前面几个方法都已试过，无效）

### ISSUE THREAD

**Issue by clayclayclay** [Haojen/hexo-theme-Anisina#35]
`Unhandled rejection ReferenceError: H:\hexo\themes\Anisina\layout\page.ejs:145
    143|     <div class="row">
    144|         <div class="col-lg-8 col-lg-offset-1 col-md-8 col-md-offset-1 col-sm-12 col-xs-12 post-container">

> > 145|             <%- page.content || body %>
> >     146|         </div>
> >     147|         
> >     148|         <div class="

body is not defined
`

把所有已有文章给删除了，再new一篇，hexo g 之后报错，重新构建hexo项目，再pull下这个主题，也不行。

**Comment by clayclayclay** [comment]
当点击categories时，也报错：
`Unhandled rejection ReferenceError: H:\hexo\themes\Anisina\layout\page.ejs:145
    143|     <div class="row">
    144|         <div class="col-lg-8 col-lg-offset-1 col-md-8 col-md-offset-1 col-sm-12 col-xs-12 post-container">

> > 145|             <%- page.content || body %>
> >     146|         </div>
> >     147|         
> >     148|         <div class="

body is not defined
`

**Comment by Haojen** [comment]
你新建的博文没有写任何内容的情况就会报这个错误
