### ISSUE TITLE
SNS Settings下输入自己weibo、zhihu的username不能打开正确的用户页面

### ISSUE THREAD

**Issue by yellowstarhx** [Haojen/hexo-theme-Anisina#39]
github的能正常打开，知乎和微博都是显示查无此人，但是在知乎和微博上都能搜到自己。
在说明文档中没有找到其它SNS设置的说明，因此提问。

**Comment by Haojen** [comment]
应该是 知乎 和 微博 都需要一个个人链接， 而不是阁下打开自己的页面后复制粘贴的那个链接，而是你自己的独立链接， 类似二级个人域名

**Comment by geyingauv** [comment]
你是不是复制了链接 只需要一个用户名就OK了
