### ISSUE TITLE
可以加上首页友链吗

### ISSUE THREAD

**Issue by justforlxz** [Haojen/hexo-theme-Anisina#4]
在首页右侧信息下面加上友链，不知道可以增加这么功能？

**Comment by Haojen** [comment]
多谢反馈，下个版本升级会考虑添加  :D

**Comment by Haojen** [comment]
@kirigayakazushin 已添加友链， 请明天下午更新版本查看，另外这次版本跨度比较大，有些兼容性的问题，明晚我会写出说明和解决办法
have good day  ：）
