### ISSUE TITLE
创建about页面出错

### ISSUE THREAD

**Issue by GHdeng** [Haojen/hexo-theme-Anisina#40]
使用hexo new page "about" 添加about界面后出现以下错误，已经是clone最新代码
Unhandled rejection ReferenceError: /Users/deng/Documents/hexoFile/ghdengdlog/themes/Anisina/layout/page.ejs:145
<div class="row">
    144|         <div class="col-lg-8 col-lg-offset-1 col-md-8 col-md-offset-1 col-sm-12 col-xs-12 post-container">
 > 145|             <%- body %>
    146|         </div>
    147|         
    148|         <div class="

body is not defined

**Comment by Haojen** [comment]
可能是由于因为你 about 页面里没有写任何东西的原因 :)

**Comment by GHdeng** [comment]
@Haojen 已经添加内容，还是出现上面那个错误。把Layout定位到tags是可以的，写成about就不行

---
title: About
date: 2016-12-01 09:21:06
layout: about
---
# 关于
这是一个关于界面
添加内容

**Comment by Haojen** [comment]
应该是因为你没有为 about 页面创建 layout ,换言之你实际上没有创建一个 about 页面

**Comment by tpblog** [comment]
请教一下，怎么设置 about 页面？有教程吗？

**Comment by MillZhang** [comment]
同请教这个问题,如何在layout中创建about?
@Haojen

**Comment by Haojen** [comment]
@tpblog  请参阅 [我下面的回答](https://github.com/Haojen/hexo-theme-Anisina/issues/52)
