### ISSUE TITLE
代码块外边有边框，是我使用的姿势不对吗？

### ISSUE THREAD

**Issue by wxiubin** [Haojen/hexo-theme-Anisina#46]
作者能否帮忙看下，我对css实在是不熟~

[博客页面地址](https://sanyucz.top/2016/05/22/multithreading_iOS/)

**Comment by Haojen** [comment]
@sanyucz  如果没有对主题进行调整的话，应该是新版主题的bug，因为我个人博客用的一直是老版本，这两天我会抽时间尽快对这个问题检查和修复
感谢使用，休假刚回来，迟到的新年快乐😁


另外我也正准备学习 iOS ，你博客内容写的真好，收藏当教程了，正好适合我这个菜鸟 :D

**Comment by wxiubin** [comment]
@Haojen 如果你准备学习iOS，我很高兴能为你提供些帮助。
我本来是想找一个Github/Gist风格的Hexo主题，结果看到Anisina，这个主题太漂亮了，我也fork了一份，也希望能学习下前端。😁

**Comment by Haojen** [comment]
@sanyucz  目前前端，不妨加个微信，互相交流一下？
我微信号 edenmoons
期待: )
