### ISSUE TITLE
首页的图片显示不准确

### ISSUE THREAD

**Issue by jarviswwong** [Haojen/hexo-theme-Anisina#5]
您好 ，更新了新版本后，首页的那张图片显示不准确 因为现在page里的每张图片都是在独立的文件夹下
比如 `http://localhost:4000/2016/05/30/Dom%20HTML/web-img.jpg`  
但是首页这张图 虽然路径是取自post的header-img 但是路径对应不上 他的路径是根目录...
比如`http://localhost:4000/web-img.jpg`  然后这样的话首页的图就显示不出来了...

**PS:** 自己找到办法..我在index.ejs 里  在`<%- post["header-img"]` 加上了 `<%- config.root %><%- post.path %>`
 **最后如下**
`<div class="post-preview <%- post.layout === 'poetry'? 'post-preview-poetry':''%>"
        style="background-image: url('<%- config["cdn-url"]%><%- config.root %><%- post.path %><%- post["header-img"] || config["post-default-img"] %><%- config["cdn-url"]?config["clip-home-post-bg"]:"" %>')">`

这样首页图就可以显示啦 :)

**Comment by jarviswwong** [comment]
如果用cdn的话 就没有这个问题咯

**Comment by Haojen** [comment]
@yyijian  感谢你反馈的这个问题，很抱歉耽搁的很久才回复你。

实际上， 这不是一个"错误"，我的意思是说当时我为了调试方便，有意而为之，只是后来自己用的CDN就忽略这个问题啦，多谢阁下的细心。

下个版本将会修复这个问题。 ：）

**Comment by Zeroxus** [comment]
hi~请问你的那个标签栏在哪里设置？

**Comment by Haojen** [comment]
@Zeroxus  new page tags ，就会有tags标签页面了。

**Comment by imzyf** [comment]
直接 hexo new page tags ，标签页面是出不来的，还要在 tags/index.md加上 layout: tags

**Comment by chengquanwei** [comment]
谁能告诉我，为什么我的菜单只有一个HOME,其它menu在哪设置，好难玩。

**Comment by xuby0615** [comment]
@chengquanwei hexo new page "标题名称"
就行了，在index.md中修改视图

**Comment by chengquanwei** [comment]
@xuby0615 原来还可以@人，成功了，谢谢

**Comment by ischaojie** [comment]
@xuby0615 应该将视图设置成什么？（新手）

**Comment by xuby0615** [comment]
@zhuzhezhe 
比如，在nav添加一个tags，就是 hexo new page "tags"
然后在source/tags中，修改index.md，在两道"---"中间添加layout: tags
就行了

**Comment by HipHopCoderS** [comment]
@imzyf   正解 @Haojen  楼主是否考虑加入搜索功能？

**Comment by Haojen** [comment]
@HipHopCoderS ，搜索是一个好功能，但由于在 github 上搭建的博客属于静态生成的，所以无法自己制作一个搜索功能，但会有类似的搜索插件可以嵌入。 这方面我的了解只限于此了，如果需求大的话说不定会加入这个功能。当然如果你迫切需要的话，可以自己添加一个试试，可以的话，也可以提一个分支合并进来。
下个版本主要添加和完善的：
- 单页面 SEO 优化
- 添加友情链接
- CDN 无缝切换（就是一个内容页你也可以用外链也可以用自己的CDN）
- 还有一些 bug 修复

另外，感谢你在微博的支持。我会做的更好的 ：）
