### ISSUE TITLE
能否支持math公式

### ISSUE THREAD

**Issue by xbotao** [Haojen/hexo-theme-Anisina#50]
不知该主题能够支持latex公式显示？

**Comment by Haojen** [comment]
@xbotao  这个还没有涉足过，不过我尽量  🤣

**Comment by xbotao** [comment]
感谢，我看一般都是使用mathjax
但是里面貌似有些坑，marked和mathjax 重合语法之间

**Comment by perixiaowan** [comment]
这个是不是跟本地markdown编辑工具有关系？只要markdown编辑工具支持math公式，在用这个主题时，发布也是可以将公式展现出来的。在我的页面中这个主题下，math公式都能正常显示


Sent from Mail Master
在2017年03月16日 17:23，Haojen Ma 写道：

@xbotao 这个还没有涉足过，不过我尽量 🤣

**Comment by perixiaowan** [comment]
不好意思，我看错了，我之前编辑的公式也没有显示出来


Sent from Mail Master
在2017年03月16日 17:23，Haojen Ma 写道：

@xbotao 这个还没有涉足过，不过我尽量 🤣

**Comment by Haojen** [comment]
@perixiaowan  好久不见，最近在忙什么？ 😁

**Comment by perixiaowan** [comment]
哈哈，跟你私聊


Sent from Mail Master
在2017年03月16日 17:49，Haojen Ma 写道：

@perixiaowan 好久不见，最近在忙什么？ 😁

**Comment by xbotao** [comment]
收到好多邮件。。。
:grin:

**Comment by whyour** [comment]
个人作品页面的data数据存在哪里。求指导
https://stonemonkey.top
@Haojen @perixiaowan @YYGCui

**Comment by Haojen** [comment]
@w-nba 这个页面的配置完全是个人用来在应聘的时候临时搭建的，所以没有写在教程里面。如果用的人多的话，说不定找个时间我来写一份。

**Comment by Haojen** [comment]
@xbotao 能否提供一份带有数学公式的 markdown 文件? 最近正在添加数学公式这个功能.
