### ISSUE TITLE
建议增加新的评论插件

### ISSUE THREAD

**Issue by AlphaMistral** [Haojen/hexo-theme-Anisina#51]
Disqus国内被不可描述, 而多说宣布将在2017年7月1日停止对多说评论插件的一切支持. 希望作者能加入对其他诸如友言等插件的支持, 谢谢!

**Comment by Haojen** [comment]
@AlphaMistral 多谢你的建议，我会另择评论插件，如果仁兄你有更好的推荐的话，也可以推荐给我哟😁

**Comment by AlphaMistral** [comment]
我这边刚刚尝试了几个, 都是各有利弊: 
1. 友言. 功能完善, 但是**不支持https**, 也就是说无法部署到github page上. 
2. 畅言. 体验上可能是这几个里最好的, 但是要求必须有**备案号** ... 
3. 网易云跟帖. **支持https**, 但是要求提供唯一一个域名, 只能支持一个站点的社会化评论. 当然也就因此不能部署到github page上了 ... 
4. 来必力. 名不见真转, 韩国开发, **可能会**不太稳定. 不过支持https, 功能上也足够. 可以到我的主页alphamistral.github.io上看看.

**Comment by Haojen** [comment]
@AlphaMistral  来比力界面看起来要比多说默认的高大上多啦，阁下写的博文真严谨。

**Comment by AlphaMistral** [comment]
多谢认同. 您的主题实用, 优雅还容易上手, 也是我Keep Blogging的一大原因. ^_^

**Comment by Haojen** [comment]
@AlphaMistral  现已添加来比力 😁
