### ISSUE TITLE
请问配置好works后怎么添加一个作品呢

### ISSUE THREAD

**Issue by tuohuang** [Haojen/hexo-theme-Anisina#52]
配置好works  works页面是空的，怎么样添加一个作品呢，像您的博客的作品集一样。

**Comment by LionSR** [comment]
同问! @perixiaowan @Haojen

**Comment by xiaoyouPrince** [comment]
同问，我也是卡在这里了@perixiaowan @Haojen

**Comment by xinghu0164** [comment]
同问，哪里有site.data.projects 呢？@Haojen

**Comment by BlankXue** [comment]
同问

**Comment by Haojen** [comment]
问这个问题的人都能建立一个讨论组了, 本来 works 页面是应聘时临时写的, 本不属主题范围之内. 
但需要的人多了, 也就成了刚需了吧,  最近在写一款 alfred 的翻译workflow, 不出意外的话, 今后两天写完. 
写完后, 我会针对这个问题, 专门写一个教程.
最后感谢大家的反馈和使用

**Comment by BlankXue** [comment]
@tuohuang @LionSR @xiaoyouPrince @xinghu0164  
小弟改造了一下 haojen 的主题。详细看我的blog http://jhai.me/2017/07/11/Anisina%E4%B8%BB%E9%A2%98%E6%94%B9%E9%80%A0/   主要引入了  hexo-generator-mypage。

**Comment by BlankXue** [comment]
@Haojen 我也不知道这样改是否合理。 http://jhai.me/2017/07/11/Anisina%E4%B8%BB%E9%A2%98%E6%94%B9%E9%80%A0/

**Comment by xiaoyouPrince** [comment]
谢谢啦，我看了你的网站啦，感觉很好，等我不忙有时间的时候按你的方法配置一下


Sent from Mail Master
在2017年07月11日 09:27，JXue 写道：

@tuohuang@LionSR@xiaoyouPrince@xinghu0164
小弟改造了一下 haojen 的主题。详细看我的blog http://jhai.me/2017/07/11/Anisina%E4%B8%BB%E9%A2%98%E6%94%B9%E9%80%A0/。主要引入了 hexo-generator-mypage。

**Comment by Haojen** [comment]
教程已出, 新写的一个hexo 主题, 教程中包含了如何创建 about 页面以及
 work 页面, [创建 Works 页面](https://github.com/Haojen/hexo-theme-Claudia#创建-about-页面)

**Comment by xiaoyouPrince** [comment]
good job！thank you。




Sent from Mail Master
在2017年07月13日 20:08，Haojen Ma 写道：

教程已出, 新写的一个hexo 主题, 教程中包含了如何创建 about 页面以及
work 页面, 创建 Works 页面
