### ISSUE TITLE
目前多说到6月份停止服务了

### ISSUE THREAD

**Issue by BlankXue** [Haojen/hexo-theme-Anisina#54]
是否更新一款评论类的插件

**Comment by Haojen** [comment]
@JHXue 放心，会在之前更新的 😁

**Comment by Haojen** [comment]
@JHXue  现已更新来比力评论插件， 使用方法可以看教程  [教程](http://haojen.github.io/2017/05/09/Anisina-%E4%B8%AD%E6%96%87%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B/) 😁
