### ISSUE TITLE
header-img无法显示的问题

### ISSUE THREAD

**Issue by Derek-X-Wang** [Haojen/hexo-theme-Anisina#55]
博主大大，

我试了半天就是不知道怎么设置让header-img正常工作。
```
---
title: Install Arduino IDE 1.8.2 in Ubuntu 16.04
date: 2017-03-27 22:54:43
header-img: arduino_uno.jpg
---
```
在_config.yml里
`post_asset_folder: true`
```
# img CDN path
cdn-url:  # 你的CDN地址
```

文件结构是这样的
<img width="198" alt="screen shot 2017-04-18 at 4 04 32 pm" src="https://cloud.githubusercontent.com/assets/6364170/25156737/54c543b2-2451-11e7-93c1-000ad9b34af4.png">

主页的404错误（最新post的preview图片）
`GET http://localhost:4000/nullarduino_uno.jpg 404 (Not Found)`
post页面的404错误
`GET http://localhost:4000/2017/03/27/Install-Arduino-IDE-1-8-2-in-Ubuntu-16-04/nullarduino_uno.jpg 404 (Not Found)`

然后，如果我加上cdn: header-off的话，在post页面header img能显示，但是在主页的还是没法显示因为path找的是根目录下的arduino_uno.jpg

我想把图片存本地，有什么解决办法吗？
多谢

**Comment by Derek-X-Wang** [comment]
看了一下源码，稍稍改了一下，可以了。

**Comment by lutein** [comment]
同样的问题，请问能告知改哪里吗？多谢哦
