### ISSUE TITLE
移动端显示有遮挡

### ISSUE THREAD

**Issue by BiYuqi** [Haojen/hexo-theme-Anisina#57]
## 浏览器：夸克浏览器，x浏览器，自带浏览器
![](http://oq4hkch8e.bkt.clouddn.com/blog-theme-bug.png)
下半区域直接不显示

**Comment by Haojen** [comment]
这个问题我还是第一次遇到，你重新部署一次试试

**Comment by whyour** [comment]
估计是浏览器问题，换个浏览器就行了。其他浏览器肯定没问题。
