### ISSUE TITLE
首页文章的默认背景图片

### ISSUE THREAD

**Issue by ghost** [Haojen/hexo-theme-Anisina#58]
您好 ，很喜欢您的主题，我遇到的一个问题是首页一打开以后，正常来说第一篇文章是有个背景图的，可是那个背景图一直是灰色的显示不出来，我填写了默认的post-default-img ，在打开文章以后，header显示背景图片又是正常的。我不知道还能改哪里，其他的地方也试过了，您能帮我解答一下吗 谢谢你 我的地址是http://xxxxxdog.github.io

**Comment by ghost** [comment]
没有用CDN  是在source下创建image文件 然后调用的 嗯嗯

**Comment by Haojen** [comment]
请您再次阅读使用文档 [https://haojen.github.io/2017/05/09/Anisina-%E4%B8%AD%E6%96%87%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B/](url)
另外，安装文档操作后，如需重新部署，务必执行 hexo deploy -g 命令，以防缓存

**Comment by hx1997** [comment]
我也遇到了这个问题，解决方法是在 _config.yml 中加入一行：

```
post-default-img-mobile: 你的图片地址
```

原因是 Anisina/layout/index.ejs 第 32 行使用的是 post-default-img-mobile 属性而非 post-default-img（因此你也可以通过把这行里的 -mobile 删掉来解决问题，但那样 -mobile 属性会失效）：
```
style="background-image: url('<%- post["header-img"] ? config["cdn-url"] + post["header-img"] : config["post-default-img-mobile"] %>')">
```
