### ISSUE TITLE
目录都不能导航啊。

### ISSUE THREAD

**Issue by haimawudi** [Haojen/hexo-theme-Anisina#59]
每一篇文章上的目录，点上去没反应

**Comment by Haojen** [comment]
你是不是用了第三方的markdown解析引擎呢？ 如果是的话，的确会出现此问题。 我个人博客因为需要演示emoji功能，所以使用了第三方的markdown解析引擎，导致了点击博文右侧目录时，无法跳转的问题。
所以只要别用第三方解析引擎，应该就不会出现这种问题的。
如果不是的话，你可以在这里更详细的描述你所遇到的问题，以便排查。

**Comment by haimawudi** [comment]
右边目录功能。右边的目录本来就是拿来导航的。点到某一个章节上面，文章就应该移到那个地方去，工人阅读。你这点目录上面的某一章节都没反应。就下面这个地址，你试试，你点右边目录，有什么反应吗？
https://haojen.github.io/2017/05/09/Anisina-中文使用教程/

**Comment by Haojen** [comment]
@haimawudi  上面不是已经告诉你了，我博客上点击目录无法跳转，这个问题是由于我个人使用了hexo第三方的mardown解析引擎导致的。所以我上面才问你，你自己的博客是否用了第三方解析引擎。

**Comment by haimawudi** [comment]
写技术博客不用markdown，用什么？

**Comment by Haojen** [comment]
@haimawudi 当然写博客的话，markdown是首选，而hexo博客系统默认提供了一种markdown解析引擎，但是也有第三方的markdown解析引擎。这就好像一种标准的制定，却有多种实现一样。

**Comment by Haojen** [comment]
或者说markdown与解析引擎的关系如同 html 与浏览器的一般

**Comment by haimawudi** [comment]
长姿势了。谢谢。
