### ISSUE TITLE
absolute path or relative path

### ISSUE THREAD

**Issue by sanmmm** [Haojen/hexo-theme-Anisina#60]
首先,很感谢作者的共享精神,模板很漂亮!
但是,我在部署的时候遇见了一些问题,看了layout下面的.ejs文件内容和 文档之后,感觉文档中对于asset(资源)的路径描述不清楚. 容易让使用者在相对路径和绝对路径的错误中绕不出来.
假设我们在hexo项目目录 /source/img/ 中放入 avatar.jpg文件 
按照文档中的用例,我们设置post-default-image: img/avatar.jpg
这样在index.html文件中会被拼接为 http://yourwebsite/img/avatar.jpg
但是在page.html文件中会被浏览器自动拼接为 http://yourwebsite/page/1/img/avatar.jpg 
即 它是以相对路径的形式嵌入到网页中的.
假如我们更改为post-default-image: /img/avatar.jpg
则当hexo在渲染模板的时候嵌入的是绝对路径,则会访问source/img/avatar.jpg
这种情况下无轮是首页还是文章页都是绝对路径,所以都能正确加载图片.

**Comment by sanmmm** [comment]
还在issue中发现 一个类似的问题  #58

**Comment by Haojen** [comment]
多谢你的反馈, 最近在忙, 等抽闲了, 再仔细的针对这个问题展开探讨, 谢谢你的支持和理解! 👍
