### ISSUE TITLE
英语 readme 页面 关于创建Tags页面出错

### ISSUE THREAD

**Issue by zhangxu999** [Haojen/hexo-theme-Anisina#61]
Create Tag page

1. use hexo command hexo new page **_"Tags"_**
2. then open yourblog/source folder , find Tags/index.md, set layout: tags
3. after use hexo cammand reset hexo hexo clean && hexo g , all done : )

Tags 是不对的，会导致 普通页面中的 tag 链接访问失败。还请修复，hexo  #新手如果看了英文文档会踩坑的

**Comment by Haojen** [comment]
@zhangxu999  多谢告知, 另外朋友的名字让我想起了一位前同事..

**Comment by zhangxu999** [comment]
@Haojen 没办法，zhangxu 泛滥~~/(ㄒoㄒ)/~~
