### ISSUE TITLE
how to use work layout ?

### ISSUE THREAD

**Issue by shakir-abdo** [Haojen/hexo-theme-Anisina#63]
hi your theme is really amazing , its simple and clean , but i'm asking how i can use the work.ejs layout ?

**Comment by BlankXue** [comment]
@shakir-abdo  You can use this，like me。http://jhai.me/2017/07/11/Anisina%E4%B8%BB%E9%A2%98%E6%94%B9%E9%80%A0/

**Comment by Haojen** [comment]
@shakir-abdo  if you wana use this layout , you mast in blog root path open `source` and then create a new folder , folder name is `work`, and then open it, and in the folder create a `index.md`
and more ,if you wanna use , contact to me, i show you , sorry , i m english just so bad , or if you can read Chinese,  can watch @JHXue  Answer
