### ISSUE TITLE
您好，首页不显示标题背景

### ISSUE THREAD

**Issue by zeech3** [Haojen/hexo-theme-Anisina#65]
如果不适用七牛云的话，设置了header-img还是不显示标题背景。

![image](https://user-images.githubusercontent.com/11804958/29059154-bfc367aa-7c46-11e7-9e86-5db646f1e8ea.png)

**Comment by fingthinking** [comment]
@Zeecoders 
![image](https://user-images.githubusercontent.com/5517388/29077584-07e132da-7c8b-11e7-87a6-ad74c9546e87.png)
查看源码可以看到，首页显示的是通过post-default-img-mobile这个属性来获取的，建议和图中类似配置。欢迎查看我的博客：[fingthinking.github.io](https://fingthinking.github.io)

**Comment by zeech3** [comment]
已经可以了！设置带mobile后缀那个就可以了

**Comment by fingthinking** [comment]
@Zeecoders 看了你的博客，redis大神呀，建议开启评论功能，参考[Anisina中文教程](http://haojen.github.io/2017/05/09/Anisina-%E4%B8%AD%E6%96%87%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B/) 5月9号更新

**Comment by zeech3** [comment]
@fingthinking 我的博客是disqus评论，国内被墙了。。

**Comment by zyczzh** [comment]
这个好像不行，这个是默认的首页图片，如果要每个文章都不一样，应该怎么调呢？根据中文文档还调整不了～
