### ISSUE TITLE
打开文章，上方的图片如何设置显示出来

### ISSUE THREAD

**Issue by chengquanwei** [Haojen/hexo-theme-Anisina#7]
打开文章的上方的图片在哪设置显示的啊，我一直在弄这个主题就这张图片不知道在哪设置显示

**Comment by jarviswwong** [comment]
在每篇文章的上方 layout部分  比如加入`header-img: "deskimage.jpg"`
图片可以用七牛 也可以放在和文章标题对应的文件夹里  每次new post的时候会生成的那个

**Comment by chengquanwei** [comment]
太感谢了，试了各种路径，终于对了
