### ISSUE TITLE
提个小建议 

### ISSUE THREAD

**Issue by SpiffyEight77** [Haojen/hexo-theme-Anisina#80]
巨巨你吼啊！
能不能给这套主题(Anisina)添加apple-touch-icon
让iOS用户可以把博客网站保存到带博客图标保存在桌面上。
望巨巨采纳！
为什么Archive页面底下的图标(git、推特)居中靠右？？？

**Comment by Haojen** [comment]
@SpiffyEight77  这个建议非常好！👍 采纳，下个版本更新应该会添加上去。 Archive 靠右的问题回头我看看，如果排版不好看，会重新调整！多谢你的反馈
