### ISSUE TITLE
Archive页面底部图标居中靠右Bug

### ISSUE THREAD

**Issue by SpiffyEight77** [Haojen/hexo-theme-Anisina#81]
1.文章内部点击标签不能跳转到Tags页面，source底下生成标签页面的文件夹名字必须是Tags否则页面就404，但是配置文件里面的却是tags(修改成Tags也404)，是因为这里的问题导致跳转失败？？(在layout里面的post把小写t改成大写T就好了)
2.archive页面底部git、Twitter等图标居中靠右(可以通过替换旧文件来解决)

**Comment by Haojen** [comment]
好的，感谢。 下个版本会尽可能的修复这些问题
