### ISSUE TITLE
work部分怎么使用

### ISSUE THREAD

**Issue by lw604217818** [Haojen/hexo-theme-Anisina#87]
hi~看大大的源码有看到works.ejs，想问下，new 出来后怎么添加？

**Comment by Doragd** [comment]
在source文件夹中新建一个md文件，然后里面写上 layout: works 就可以渲染了(●'◡'●)

**Comment by lw604217818** [comment]
我这样试过，不行，这样只能把页面渲染出来，但是这个页面加不进去内容

**Comment by kentsx** [comment]
参考我写的文章：[HEXO Anisina主题下Work页面设置](https://kentspace.xyz/2018/2018-4-1-HEXO-Anisina%E4%B8%BB%E9%A2%98%E4%B8%8BWork%E9%A1%B5%E9%9D%A2%E8%AE%BE%E7%BD%AE/)
