### ISSUE TITLE
移动端H5页面有位移[iOS & Safari & iPhone X]

### ISSUE THREAD

**Issue by KyleCe** [Haojen/hexo-theme-Anisina#88]
如题
移动页面往左可以移出偏移，往右没有这问题；横屏之后也没有这问题

![1611520527725_](https://user-images.githubusercontent.com/8437760/37164262-c18d1ab4-2334-11e8-9cc0-f7e803534d32.jpg)

**Comment by Haojen** [comment]
这是一个Bug，我之前貌似也遇到过，感谢你的反馈，后续有时间的话会修复这个问题
