### ISSUE TITLE
导航栏的按钮顺序可以控制么

### ISSUE THREAD

**Issue by JammeLee** [Haojen/hexo-theme-Anisina#89]
找了一下源码，但是好像看不太懂js，所以也不知道到底怎么控制。[手动尴尬]

**Comment by JammeLee** [comment]
emmm...就是HOME TAGS ABOUT这类按钮。
`
        <div id="huxblog_navbar">
            <div class="navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="<%= config.root %>">Home</a>
                    </li>
					<% var about = false; %>
                    <% site.pages.forEach(function(page){ %>
                        <% if(page.title){ %>
							<% if(page.title == "about") { %>
								<% about = true; %>
							<% } else { %>
                        <li>
                            <a href="<%= config.root %><%= page.path.replace('index.html', '') %>"><%= page.title %></a>
                        </li>
							<% } %>
						<% } %>
                    <% }); %>
					
					<% if (about == true) { %>
						<li>
							<a href="<%- url_for(config.root + 'about') %>">About</a>
						</li>
					<% } %>
                </ul>
            </div>
        </div>
    </div>`

**Comment by JammeLee** [comment]
emmm...就是HOME TAGS ABOUT这类按钮。
`

        <div id="huxblog_navbar">
            <div class="navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="<%= config.root %>">Home</a>
                    </li>
					<% var about = false; %>
                    <% site.pages.forEach(function(page){ %>
                        <% if(page.title){ %>
							<% if(page.title == "about") { %>
								<% about = true; %>
							<% } else { %>
                        <li>
                            <a href="<%= config.root %><%= page.path.replace('index.html', '') %>"><%= page.title %></a>
                        </li>
							<% } %>
						<% } %>
                    <% }); %>
					
					<% if (about == true) { %>
						<li>
							<a href="<%- url_for(config.root + 'about') %>">About</a>
						</li>
					<% } %>
                </ul>
            </div>
        </div>
    </div>
`

**Comment by Haojen** [comment]
可以，如果动手能力强的话，可以修改代码的顺序实现。祝你成功！
