### ISSUE TITLE
主页文章背景图片无法显示问题

### ISSUE THREAD

**Issue by Marlous** [Haojen/hexo-theme-Anisina#93]
每篇博文点进去背景图片正常，但主页背景图片无法显示。相关配置如下：
`header-img: //s1.ax1x.com/2018/06/08/CHqLn0.jpg`
`post-default-img: "/img/post-default-sky.jpg"`

**Comment by Haojen** [comment]
是不是少了前缀？ 请参考我博客的Anisina使用教程，谢谢你的使用 👍
